# Generated by Django 5.2.12 on 2026-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_types', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('tranaction_category', models.CharField(choices=[('sales', 'Sales'), ('operations', 'Operations'), ('payroll', 'Payroll'), ('assets', 'Assets')], max_length=10)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
