# Generated by Django 5.2.12 on 2026-03-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='tranaction_category',
            new_name='transaction_category',
        ),
    ]
